services:
  - type: web
    name: psychology-crm
    runtime: node
    buildCommand: npm install && cd client && npm install && npm run build && cd .. && ls -la client/build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_PATH
        value: ./database.sqlite
